# Generated by Django 4.1.2 on 2022-10-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('resim', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('modelNo', models.CharField(max_length=50)),
                ('isletimSistemi', models.CharField(max_length=50)),
                ('islemciTipi', models.CharField(max_length=50)),
                ('ram', models.SmallIntegerField(max_length=50)),
                ('diskBoyutu', models.SmallIntegerField(max_length=50)),
                ('diskTuru', models.CharField(max_length=10)),
                ('ekranBoyutu', models.DecimalField(decimal_places=2, max_digits=2)),
                ('puan', models.DecimalField(decimal_places=1, max_digits=1)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('urunLink', models.CharField(max_length=1000)),
                ('urunSite', models.CharField(max_length=200)),
            ],
        ),
    ]
