# Generated by Django 4.1.2 on 2022-10-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='islemciNesli',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='diskBoyutu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(max_length=50),
        ),
    ]
