# Generated by Django 4.1.2 on 2022-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_notebook_islemcinesli_alter_notebook_diskboyutu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='diskBoyutu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='diskTuru',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ekranBoyutu',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='islemciTipi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='isletimSistemi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='marka',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='modelNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='puan',
            field=models.DecimalField(decimal_places=1, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='resim',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='urunLink',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='urunSite',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
