# Generated by Django 4.1.2 on 2022-10-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_alter_notebook_diskboyutu_alter_notebook_diskturu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='ekranBoyutu',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fiyat',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='puan',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
