# Generated by Django 4.1.2 on 2022-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_alter_notebook_ekranboyutu_alter_notebook_fiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='ekranBoyutu',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fiyat',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='puan',
            field=models.DecimalField(decimal_places=3, max_digits=13, null=True),
        ),
    ]
