# Generated by Django 4.1.2 on 2022-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_alter_notebook_ekranboyutu_alter_notebook_fiyat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='ekranBoyutu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fiyat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='puan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
